FROM ubuntu

RUN apt update -q
RUN apt install -yq fish vim git wget curl
RUN chsh -s /usr/bin/fish
RUN curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
RUN curl -L https://get.oh-my.fish > install
RUN /usr/bin/fish install --noninteractive --path=~/.local/share/omf --config=~/.config/omf
RUN rm /install
RUN curl -Lo ~/.config/fish/functions/getopts.fish --create-dirs git.io/getopts


CMD [ "/usr/bin/fish" ]
